### ISSUE TITLE
add a button to select agent models

### ISSUE THREAD

**Issue by nickofra123** [degeneratehyperbola/NEPS#134]
add button for change player model

**Comment by SK0lll** [comment]
There was an option for it in skinchanger but its commented out

@degeneratehyperbola did it cause crashes or something else ?

**Comment by degeneratehyperbola** [comment]
Yes it does cause crashes due to game not finding some models. The model list needs to be updated with each little alteration to their paths and/or addition of new ones, and it is a bit painful in one certain spot called ass. If someone has an updated list of models, I would be grateful if I got a hold of it.
