### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sgamesdev** [degeneratehyperbola/NEPS#154]
When I am trying too build the dll, i get these 2 errors 
![image](https://github.com/degeneratehyperbola/NEPS/assets/72159024/94172fb1-02b9-4abb-9c9c-3cabda6b4954)

**Comment by degeneratehyperbola** [comment]
This issue is due to stupid MSVC update that doesn't allow turning exceptions off anymore.
# In the meanwhile
- Make sure you are editing all configs. This should say "All configurations"
![image](https://github.com/degeneratehyperbola/NEPS/assets/65950527/5de7e317-d8f7-4713-a280-8c18eb28ab21)
- **<ins>Enable</ins>** exceptions in the project
![image](https://github.com/degeneratehyperbola/NEPS/assets/65950527/27fbe650-af60-4c09-bc79-329c9e95f231)
- And check preprocessor definitions for _HAS_EXCEPTIONS=0 and **<ins>remove</ins>** that definition
![image](https://github.com/degeneratehyperbola/NEPS/assets/65950527/c41cbf3b-63a5-46b4-a23b-79ce115fe928)

**Comment by sgamesdev** [comment]
It works now , thanks for the fix
