### ISSUE TITLE
Useful things to be added :)

### ISSUE THREAD

**Issue by RiskyOnTinder** [degeneratehyperbola/NEPS#23]
**1.**
A nice idea for the cheat will be to isolate the skins config to the main config. This will be better for sharing ur skin config or applying it to all your configs. For example, something like the main config menu could be added into the skinchanger tab.

**2.**
A nice addition to avoid a lot of crashes will be to change the cheat a bit if possible to modify the visuals after the load of the map. I am saying this because i use the custom skybox, worlds color, props color and sky color and when I have the changes enabled when loading into a game the chances of crashing are high. Everytime I go to a game i disable them before to be able to get into with no crashes. In my opinion, modifying them after the load is complete would be a good fix if it is even possible.

**3.**
Anti-aim indicator would be a nice addition. Something like an arrow to the right or left depending on the real angle that you got, so it would be easier to check your real angle without going into third person.

Keep up the good work, your project is awesome :D

**Comment by degeneratehyperbola** [comment]
Hey, thanks for the feedback!
As for now NEPS has "Incremental load" functionality which allows you to have every aspect of the cheat in separate configs (e. g. aimbot separate from anti-aim). Given two configs, one with say anti-aim configured and other with skins only, this feature will allow you to load the first config as a base, enable incremental load and append current config with whatever is configured in the second one.
Regarding crashes, are you sure they happen because of visual features? Recently I had a couple of problems there and was able to fix all of them regarding crashes (one was because of purchase list the other because of miss counter). Make sure you are using the latest version (still unstable) or the latest release (most stable)

**Comment by RiskyOnTinder** [comment]
Oh OK thanks I will look at that. The anti aim indicator would be a nice addition tho :)

**Comment by RiskyOnTinder** [comment]
Btw a nice addition would be double tap option. It is an exploit where u shoot 2 bullets at once. it gives an advantage for hvh
