### ISSUE TITLE
VAC was unable to verify the game session

### ISSUE THREAD

**Issue by RiskyOnTinder** [degeneratehyperbola/NEPS#24]
**VAC error**
After the new updates after some minutes ingame I get disconnected with a VAC error and i got to verify the game files everytime. Before the updates everything was fine. Moreover, my friends also get the same issue.
![image](https://user-images.githubusercontent.com/69758103/118392287-8d055b00-b641-11eb-8080-c72c08f914c1.png)

**Comment by degeneratehyperbola** [comment]
Happens a lot even with VAC bypass, because it is a product of a server-side anti-cheat. Make sure you weren't using more than 30deg aimbot or desync anti-aim, other reasons for this are unknown for now. Also instead of verifying game files you can just change accounts back and forth, that also works.

**Comment by RiskyOnTinder** [comment]
Oh OK thanks for the help
