### ISSUE TITLE
csgo crashes after injection

### ISSUE THREAD

**Issue by akine0** [degeneratehyperbola/NEPS#26]
xenos/kirin/nloader does not working
what should i do?

**Comment by akine0** [comment]
Xenos with the enabled "Ignore TLS" option doesnt work too

**Comment by degeneratehyperbola** [comment]
Did you compile NEPS by yourself? If so it'll be easy to fix.
CS:GO crashes because your processor doesn't support Advanced Vector Extensions 2 instruction set.
### To fix this:
- Go to Project->NEPS properties
![image](https://user-images.githubusercontent.com/65950527/118515484-1c903400-b73e-11eb-95a5-feae727e510b.png)
- Then go to Code Generation here
![image](https://user-images.githubusercontent.com/65950527/118515708-4b0e0f00-b73e-11eb-9d52-c57146c8195b.png)
- And change this to whatever your processor supports (I recommend SSE2 or AVX)
![image](https://user-images.githubusercontent.com/65950527/118515861-74c73600-b73e-11eb-902f-aa984351b25a.png)
- Also make sure that you are compiling in Release
![image](https://user-images.githubusercontent.com/65950527/118516116-b35cf080-b73e-11eb-9597-eb783e213614.png)
