### ISSUE TITLE
Have you considered multilingual translation?

### ISSUE THREAD

**Issue by pigeon-cn-0** [degeneratehyperbola/NEPS#6]

**Comment by degeneratehyperbola** [comment]
Oh yeah, I actually have. This is surely a great idea. But in order to even start translating I need to implement a localization system, which will take some time. For now it is only in my "to do" list.
In detail, I planned to make a raw system and let other contributors do the translations themselves or perhaps replace all GUI labels to use the system's definitions as NEPS sure does have a lot of features :)

**Comment by pigeon-cn-0** [comment]
Do you have any guidance on translation

**Comment by degeneratehyperbola** [comment]
The localization system is not planned in near future, might get reopened sometime <3
